name: pymultifracs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy>=1.17.3
  - scipy>=1.3.1
  - pywavelets>=1.1.1
  - seaborn>=0.9.0
  - scikit-learn>=0.21.34
  - statsmodels
  - pip
  - pip:
    - recombinator