version: 2.1

jobs:
  build-and-test:
    docker:
      -image: continuumio/miniconda3:latest
    executor: python/default
    steps:
      - checkout
      - restore_cache:
        keys:
        - m2-{{ checksum "meta.yml" }}
      - run:
        command: |
          conda env update -f meta.yml
        name: install dependencies
      - save_cache:
        key: m2-{{ checksum "meta.yml" }}
        paths:
        - /home/circleci/.local/lib/

workflows:
  main:
    jobs:
      - build-and-test
