version: 2.1

jobs:
  build-and-test:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "meta.yml" }}
      - run:
          command: |
            conda env update -f meta.yml --name base
            conda install -c conda-forge pytest
            conda list
          name: install dependencies
      - save_cache:
          key: m2-{{ checksum "meta.yml" }}
          paths:
            - /home/miniconda/
      - run:
          name: test
          command: |
            pytest -l
  docs:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Complete checkout + merge
          command: |
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            git config --global user.name "$GIT_AUTHOR_NAME"
            branch=$(git symbolic-ref HEAD)
            git checkout gh-pages
            git merge $branch
      - restore_cache:
          keys:
            - docs1-{{ checksum "meta.yml" }}
      - run:
          command: |
            conda env update -f meta.yml --name base
            conda install -c conda-forge pytest
            conda install -c conda-forge sphinx-autodoc-typehints numpydoc
            pip install sphinx-boostrap-theme
            conda install -c conda-forge nbsphinx
            conda list
          name: install dependencies
      - save_cache:
          key: docs1-{{ checksum "meta.yml" }}
          paths:
            - /home/miniconda/
      - run:
          name: Build doc + move
          command: |
            cd doc
            make html
            mv doc/html docs/

workflows:
  main:
    jobs:
      - build-and-test
      - docs